# Generated by Django 4.0.2 on 2022-06-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('godzina_rozpoczencia', models.CharField(max_length=5)),
                ('czas_przeznaczony', models.CharField(max_length=5)),
            ],
        ),
    ]
