# Generated by Django 4.0.2 on 2022-06-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taski',
            name='kategorie',
            field=models.CharField(choices=[('os', 'Osobiste'), ('pr', 'Praca'), ('sz', 'Szkoła')], default='os', max_length=2),
        ),
    ]
