# Generated by Django 4.0.2 on 2022-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menago', '0002_taski_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taski',
            name='kategorie',
            field=models.CharField(choices=[('Osobiste', 'Osobiste'), ('Praca', 'Praca'), ('Szkoła', 'Szkoła')], default='Osobiste', max_length=10),
        ),
    ]
