# Generated by Django 4.0.2 on 2022-06-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menago', '0003_alter_taski_kategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taski',
            name='czas_przeznaczony',
            field=models.CharField(max_length=10),
        ),
    ]
