# Generated by Django 4.0.2 on 2022-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menago', '0004_alter_taski_czas_przeznaczony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taski',
            name='czas_przeznaczony',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='taski',
            name='nazwa',
            field=models.CharField(max_length=50),
        ),
    ]
